//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public abstract class EstadoPedido {
	public Object PENDIENTE_DESPACHO;
	public Object DESPACHADO_EN_PERSONA;
	public Object DESPACHADO_EN_LOGISTICA;
	public Object CANCELADO;
}
