package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public enum EstadoPedido {
	CANCELADO,
	FALTA_STOCK,
	PENDIENTE_EN_PERSONA,
	PENDIENTE_EN_LOGISTICA,
	DESPACHADO_EN_PERSONA,
	DESPACHADO_EN_LOGISTICA
}
