//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : OrdenDeCompra.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//



public class OrdenDeCompra {
	private Integer idOrdenDeCompra;
	private Producto producto;
	private Date fechaEmitida;
	private boolean ordenActiva;
	private int cantidadOrdenada;
	private Remito remito;
	private List<OrdenRecepcionItem> recepcionesDelProducto;
	public OrdenDeCompraDTO toDTO() {
	
	}
	
	public OrdenDeCompra save() {
	
	}
	
	public boolean estoyActivo() {
	
	}
	
	public boolean tengoProducto(int codigoBarras) {
	
	}
	
	public void recepcionarCompra(int cantidad) {
	
	}
	
	private void altaRemitoWhenTodoRecibido(Object RemitoDTO remito) {
	
	}
	
	public int getTotalRecibido() {
	
	}
}
