package model;

import dao.ProductoDAO;
import dao.ProveedorDAO;
import dto.PedidoItemDTO;
import exceptions.ProductoException;
import exceptions.ProveedorException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class PedidoItem {
	private Integer idPedidoItem;
	private Producto producto;
	private int cantidad;
	
	public PedidoItem () {}
	
	public PedidoItem (PedidoItemDTO dto) {
		
		Producto model;
		//Proveedor proveedorModel;
		this.idPedidoItem = dto.getIdPedidoItem();
		try {
			model = ProductoDAO.getInstancia().buscar(dto.getProducto().getIdProducto());
			this.producto = model;
			
			Proveedor p = model.getProveedor();
			System.out.println("ProveedorId: " + p.getIdProveedor());
			System.out.println("Nombre: " + p.getNombre());
			System.out.println("url: " + p.getUrl());
			System.out.println("apiKey: " + p.getApiKey());
			System.out.println("estadoActivo: " + p.getEstadoActivo());
			System.out.println("idComoSuCliente: " + p.getIdComoSuCliente());
			
			
			
			
			
		} catch (ProductoException e) {
			e.printStackTrace();
		}
		
		
		/*try {
			proveedorModel = ProveedorDAO.getInstancia().buscar(dto.getProducto().getProveedor().getIdProveedor());
			this.producto.setProveedor(proveedorModel);
		} catch (ProveedorException e) {
			e.printStackTrace();
		}
		
		this.cantidad = dto.getCantidad();*/
		
		
	}
	
	public Integer getIdPedidoItem() {
		return idPedidoItem;
	}



	public void setIdPedidoItem(Integer idPedidoItem) {
		this.idPedidoItem = idPedidoItem;
	}



	public Producto getProducto() {
		return producto;
	}



	public void setProducto(Producto producto) {
		this.producto = producto;
	}



	public int getCantidad() {
		return cantidad;
	}



	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	
	/*public PedidoItem save() {
		PedidoItem item = PedidoItemDAO.getInstancia.getInstancia().save(this);
		
		return item;
	}*/



	public PedidoItemDTO toDTO() {
		PedidoItemDTO item = new PedidoItemDTO();
		item.setCantidad(this.getCantidad());
		item.setIdPedidoItem(this.getIdPedidoItem());
		item.setProducto(this.getProducto().toDTO());

		return item;
	}
	
	
}
