//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class Pedido {
	private Integer idPedido;
	private date fecha;
	private EstadoPedido estadoPedido;
	private String direccionEnvioCoordinado;
	private List<ItemPedidoDeExpedicion> items;
	public void toDTO(): PedidoDeExpedicionDTO() {
	
	}
	
	public Pedido save() {
	
	}
	
	public void despacharEnPersona() {
	
	}
	
	public void despacharEnLogistica() {
	
	}
	
	public BigDecimal getTotal() {
	
	}
	
	public void agregarItem(item PedidoItem) {
	
	}
	
	public boolean poseoElProducto(String codigoBarras) {
	
	}
}
