package model;

import dao.ProductoDAO;
import dto.PedidoItemDTO;
import exceptions.ProductoException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class PedidoItem {
	private Integer idPedidoItem;
	private Producto producto;
	private int cantidad;
	
	public PedidoItem () {}
	
	public PedidoItem (PedidoItemDTO dto) {
		
		Producto model;
		this.idPedidoItem = dto.getIdPedidoItem();
		try {
			model = ProductoDAO.getInstancia().buscar(dto.getProducto().getIdProducto());
			this.producto = model;
		} catch (ProductoException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		this.cantidad = dto.getCantidad();
		
		
	}
	
	public Integer getIdPedidoItem() {
		return idPedidoItem;
	}



	public void setIdPedidoItem(Integer idPedidoItem) {
		this.idPedidoItem = idPedidoItem;
	}



	public Producto getProducto() {
		return producto;
	}



	public void setProducto(Producto producto) {
		this.producto = producto;
	}



	public int getCantidad() {
		return cantidad;
	}



	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	
	/*public PedidoItem save() {
		PedidoItem item = PedidoItemDAO.getInstancia.getInstancia().save(this);
		
		return item;
	}*/



	public PedidoItemDTO toDTO() {
		PedidoItemDTO item = new PedidoItemDTO();
		item.setCantidad(this.getCantidad());
		item.setIdPedidoItem(this.getIdPedidoItem());
		item.setProducto(this.getProducto().toDTO());

		return item;
	}
	
	
}
