package model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//



/*
 * se asume que si Direccion está vacio, se despacha en persona, pero ante la duda se crea el boolean
 * de tPersonaYfLogistica para aclarar su estado.
 */
public class Pedido {
	private Integer idPedido;
	private Date fecha;
	private EstadoPedido estadoPedido;
	private boolean tPersonaYfLogistica;
	private String direccionEnvioCoordinado;
	private List<PedidoItem> items;
	public void toDTO(): PedidoDTO() {
	
	}
	
	public Pedido save() {
	
	}
	
	public void despacharEnPersona() {
	
	}
	
	public void despacharEnLogistica() {
	
	}
	
	public BigDecimal getTotal() {
	
	}
	
	public void agregarItem(PedidoItem item) {
	
	}
	
	public boolean poseoElProducto(String codigoBarras) {
	
	}
}
