package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class PedidoItem {
	private Integer idPedidoItem;
	private Producto producto;
	private int cantidad;
	public PedidoItemDTO toDTO() {
	
	}
}
