package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class Remito {
	private Integer idRemito;
	private date fecha;
	private List<RemitoItem> productosRecibidos;
	public RemitoDTO toDTO() {
	
	}
	
	public Remito save() {
	
	}
	
	public void agregarProducto(int idProducto, int cantidad) {
	
	}
	
	public boolean poseoProducto(int idProducto) {
	
	}
	
	public int cantidadRecibidaDelProducto(Object idProducto) {
	
	}
}
