package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class RemitoItem {
	private Integer idItemRecibo;
	private Producto producto;
	private int cantidad;
	public RemitoItemDTO toDTO() {
	
	}
	
	public int getIdProducto() {
	
	}
	
	public int getCantidad() {
	
	}
}
