//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : ComprasControlador.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//



public class ComprasControlador {
	public static ComprasControlador instancia;
	public ProductoControlador getInstancia() {
	
	}
	
	public void ComprasControlador() {
	
	}
	
	public List<OrdenDeCompraDTO> findAllOrdenesDeCompra() {
	
	}
	
	public List<OrdenDeCompraDTO> findAllOrdenesDeCompraActivas() {
	
	}
	
	public void altaOrdenDeCompra(orden OrdenDeCompraDTO) {
	
	}
	
	public void altaRemito(Object RemitoDTO remito) {
	
	}
	
	public String recepcionarCompra(int codigoBarras, int cantidad) {
	
	}
	
	public void recepcionarCompraCreandoOrden(int codigoBarras, int cantidad) {
	
	}
	
	private List<OrdenDeCompra> buscarOrdenesActivasByProducto(int codigoBarras) {
	
	}
}
