package controlador;

import java.util.Date;
import java.util.List;

import dto.OrdenDeCompraDTO;
import model.OrdenDeCompra;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class ComprasControlador {
	
	public static ComprasControlador instancia;
	
	public ComprasControlador() {		
	}
	
	public static ComprasControlador getInstancia() {
		if (instancia == null) {
			instancia = new ComprasControlador();
		}
		return instancia;
	}	
	
	public List<OrdenDeCompraDTO> findAllOrdenesDeCompra() {
	
	}
	
	public List<OrdenDeCompraDTO> findAllOrdenesDeCompraActivas() {
	
	}
	
	/*
	 * dto.setIdOrdenDeCompra(null);
	 * dto.setProducto(item.toDTO());
	 * dto.setFechaEmitida(new Date());
	 * dto.setOrdenActiva(true);
	 * dto.setCantidadOrdenada(deboPedir);					
	 * dto.setRemito(null);
	 * dto.setRecepcionesDelProducto(null);
	 * 
	 * TODO
	 * Inicializar Listas y crear Remito
	 */
	public void altaOrdenDeCompra(OrdenDeCompraDTO orden) {
	
	}
	
	public void altaRemito(RemitoDTO remito) {
	
	}
	
	public String recepcionarCompra(String codigoBarras, int cantidad) {
	
	}
	
	public void recepcionarCompraCreandoOrden(String codigoBarras, int cantidad) {
	
	}
	
	/*
	 * Devuelve las ordenes de compras activas del producto buscado
	 */
	public List<OrdenDeCompraDTO> buscarOrdenesActivasByProducto(String codigoBarras) {
	
	}
	
	/*
	 * Devuelve la cantidad ordenada activa del producto buscado
	 */
	public int buscarOrdenesActivasByProductoCantidad(String codigoBarras) {
		
	}
}
