package controlador;

import java.util.ArrayList;
import java.util.List;

import dao.PedidoDAO;
import dto.PedidoDTO;
import model.Pedido;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : Producto.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class ExpedicionControlador {
	public static ExpedicionControlador instancia;
	public ExpedicionControlador getInstancia() {
		if (instancia == null) {
			instancia = new ExpedicionControlador();
		}
		return instancia;
	}
	
	private void ExpedicionControlador() {
		
	}
	
	public List<Pedido> findAllPedidos() {
		List<PedidoDTO> pedidos = new ArrayList<PedidoDTO>();
		
		try {
			for (Pedido ped : PedidoDAO.getInstancia().getAll()) {
				pedidos.add(ped.toDTO());
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	
		return pedidos;
	}
	
	//La idea era un list de 2 variables, será con alta pedido y fue
	/*public boolean realizarVenta(List<String codigoBarras, int cantidad>, String direccionEnvioCoordinado) {
	
	}*/
	
	public int altaPedido(PedidoDTO pedido) {
		Pedido pedidito = new Pedido(pedido);
		
		return null;
	}
	
	public void bajaPedido(PedidoDTO pedido) {
	
	}
	
	public void modificarPedido(PedidoDTO pedido) {
	
	}
	
	public PedidoDTO buscarPedido(Integer idPedido) {
	
	}
	
	public void despacharEnPersona(Integer idPedido) {
	
	}
	
	public void despacharEnLogistica(Integer idPedido) {
	
	}
	
	public boolean cancelarPedidoPendiente(PedidoDTO pedido) {
	
	}
	
	public PedidoDTO buscarPedidoByDireccionEnvioCoordinado(String direccion) {
	
	}
}
