package controlador;

import java.util.List;

import dto.ProveedorDTO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Almacén
//  @ File Name : ProveedorControlador.java
//  @ Date : @Sept2018
//  @ Author : @Grupo 1
//		Boujon Di Maio, Antonella.
//		Gomila, Tomas Guido.		
//		Graue, Florencia.
//		Retamar, Nicolas.
//
//




public class ProveedorControlador {
	public static ProveedorControlador instancia;
	public ProveedorControlador getInstancia() {
	
	}
	
	public void ProveedorControlador() {
		
	}
	
	public List<ProveedorDTO> findAllProveedores() {
		
	}
	
	public Integer altaProveedor(ProveedorDTO proveedor) {
	
	}
	
	public void bajaProveedor(Integer idProveedor) {
	
	}
	
	public void modificarProveedor(ProveedorDTO proveedor) {
	
	}
	
	public ProveedorDTO buscarProveedorById(Integer idProveedor) {
	
	}
	
	public ProductoDTO buscarProductoByUrl(String url) {
	
	}
}
